//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MUDBug.Models
{
    public partial class File_growth
    {
        public int FileGrowthID { get; set; }
        public string Physical_Name { get; set; }
        public Nullable<int> Size_in_MB { get; set; }
        public Nullable<int> Size_in_GB { get; set; }
        public Nullable<System.DateTime> Reading_date { get; set; }
    }
    
}
