//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MUDBug.Models
{
    public partial class MUDBugErrorLog
    {
        public int DayID { get; set; }
        public string EventStatus { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string EVENT { get; set; }
    }
    
}
