//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MUDBug.Models
{
    public partial class ProcdureExecutionTime
    {
        public int ProdExecTimeID { get; set; }
        public string dbname { get; set; }
        public string spname { get; set; }
        public Nullable<long> ExeCount { get; set; }
        public Nullable<long> ExePerSec { get; set; }
        public Nullable<long> AvgWorkerTime { get; set; }
        public Nullable<long> TotalWorkerTime { get; set; }
        public Nullable<long> AvgElapsedTime { get; set; }
        public Nullable<long> MaxLogicalReads { get; set; }
        public Nullable<long> MaxLogicalWrites { get; set; }
        public Nullable<long> TotalPhysicalReads { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
    }
    
}
